# Generated by Django 5.0.6 on 2024-07-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajel', '0002_alter_zajelmessage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zajelmessage',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='zajel.zajelgroup'),
        ),
    ]
