# Generated by Django 5.0.6 on 2024-07-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajel', '0003_alter_zajelmessage_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zajelmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
