# Generated by Django 5.0.6 on 2024-07-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajel', '0005_zajelmessage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zajelmessage',
            name='title',
        ),
        migrations.AlterField(
            model_name='zajelmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
