# Generated by Django 5.0.6 on 2024-07-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zajel', '0006_remove_zajelmessage_title_alter_zajelmessage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zajelmessage',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='zajelgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='zajelgroup',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='zajelgroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='zajelgroup',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
